# Generated by Django 2.2.28 on 2024-01-11 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitee_id', models.CharField(max_length=100, verbose_name='GiteeID')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='签名')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name': 'meetings_user',
                'verbose_name_plural': 'meetings_user',
                'db_table': 'meetings_user',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='sig组名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'meetings_group',
                'verbose_name_plural': 'meetings_group',
                'db_table': 'meetings_group',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=12, verbose_name='会议id')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='播放地址')),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True, verbose_name='缩略图')),
            ],
            options={
                'verbose_name': 'meetings_record',
                'verbose_name_plural': 'meetings_record',
                'db_table': 'meetings_record',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=12, verbose_name='会议id')),
                ('topic', models.CharField(max_length=50, verbose_name='会议名称')),
                ('community', models.CharField(blank=True, max_length=40, null=True, verbose_name='社区')),
                ('group_name', models.CharField(max_length=50, verbose_name='所属sig组')),
                ('agenda', models.TextField(blank=True, null=True, verbose_name='会议简介')),
                ('attenders', models.TextField(blank=True, null=True, verbose_name='参会人')),
                ('start', models.CharField(blank=True, max_length=30, null=True, verbose_name='记录开始时间')),
                ('end', models.CharField(blank=True, max_length=30, null=True, verbose_name='记录结束时间')),
                ('total_size', models.IntegerField(blank=True, null=True, verbose_name='总文件大小')),
                ('download_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='下载地址')),
                ('replay_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='回放地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'meetings_video',
                'verbose_name_plural': 'meetings_video',
                'db_table': 'meetings_video',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='会议主题')),
                ('community', models.CharField(blank=True, max_length=40, null=True, verbose_name='社区')),
                ('group_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='SIG组')),
                ('sponsor', models.CharField(max_length=20, verbose_name='发起人')),
                ('date', models.CharField(max_length=30, verbose_name='会议日期')),
                ('start', models.CharField(max_length=30, verbose_name='会议开始时间')),
                ('end', models.CharField(max_length=30, verbose_name='会议结束时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='会议时长')),
                ('agenda', models.TextField(blank=True, default='', null=True, verbose_name='议程')),
                ('etherpad', models.CharField(blank=True, max_length=255, null=True, verbose_name='etherpad')),
                ('emaillist', models.TextField(blank=True, null=True, verbose_name='邮件列表')),
                ('host_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='host_id')),
                ('mid', models.CharField(max_length=20, verbose_name='会议id')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True, verbose_name='时区')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('start_url', models.TextField(blank=True, null=True, verbose_name='开启会议url')),
                ('join_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='进入会议url')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('mplatform', models.CharField(blank=True, default='zoom', max_length=20, null=True, verbose_name='第三方会议平台')),
                ('sequence', models.IntegerField(default=0, verbose_name='序列号')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opengauss.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meetings_meeting',
                'verbose_name_plural': 'meetings_meeting',
                'db_table': 'meetings_meeting',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opengauss.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meetings_groupuser',
                'verbose_name_plural': 'meetings_groupuser',
                'db_table': 'meetings_groupuser',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
