# Generated by Django 2.2.28 on 2023-11-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='career_direction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unionid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='working_years',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wx_account',
        ),
        migrations.AddField(
            model_name='user',
            name='agree_privacy_app_policy_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='同意隐私政策应用版本'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='user',
            name='logoff_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='注销时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刷新签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='revoke_agreement_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤销同意隐私声明时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='group_name',
            field=models.CharField(default='', max_length=40, verbose_name='SIG组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.SmallIntegerField(choices=[(1, '普通用户'), (2, '活动发起人'), (3, '管理员')], default=1, verbose_name='活动权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '普通用户'), (2, '授权用户'), (3, '管理员')], default=1, verbose_name='会议权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='签名'),
        ),
    ]
