# Generated by Django 2.2.28 on 2023-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openeuler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unionid',
        ),
        migrations.AddField(
            model_name='user',
            name='revoke_agreement_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤销同意隐私声明时间'),
        ),
    ]
