# Generated by Django 2.2.28 on 2023-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openeuler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='openid'),
        ),
    ]
