# Generated by Django 2.2.28 on 2023-11-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openeuler', '0002_auto_20231025_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='app_home_page',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='group',
            name='irc',
        ),
        migrations.RemoveField(
            model_name='group',
            name='owners',
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '普通用户'), (2, '授权用户'), (3, '管理员')], default=1, verbose_name='会议权限'),
        ),
    ]
