# Generated by Django 2.2.28 on 2023-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openeuler', '0003_auto_20231107_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刷新签名'),
        ),
    ]
