# Generated by Django 2.2.28 on 2023-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openeuler', '0005_user_agree_privacy_app_policy_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.CharField(max_length=128, verbose_name='会议名称'),
        ),
    ]
