# Generated by Django 2.2.28 on 2024-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openeuler', '0006_auto_20231118_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='replay_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='回放地址')
        ),
        migrations.AddField(
            model_name='video',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')
        ),
    ]
